version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/gatling-test-example
    steps:
      - checkout
      - restore_cache:
          paths:
            - ~/.m2
          key: gatling-test-example-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - run: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: gatling-test-example-{{ checksum "pom.xml" }}