apiVersion: batch/v1
kind: Job
metadata:
  name: gatling-test-example
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: gatling-test-example
          image: jecklgamis/gatling-test-example
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: "{{ java_opts }}"
            - name: SIMULATION_NAME
              value: "{{ simulation_name }}"
      restartPolicy: Never

