name: Build
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7.0.1
      - name: Set up JDK
        uses: actions/setup-java@v6.0.0
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
